# Generated by Django 5.2 on 2025-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='classification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
